export const SNAKE_MOVE = 'SNAKE/MOVE';
export const RAT_GENERATE = 'RAT/GENERATE';
export const CHANGE_DIRECTION = 'CHANGE/DIRECTION';
export const BUTTON_DISABLED = 'BUTTON/DISABLED';
export const MODAL_VISIBLE = 'MODAL/VISIBLE';
export const DIFFICULTY_GRADE = 'DIFFICULTY/GRADE'